version: '3'
services:
#BACKEND
  backend:
   build:
     context: ./backend
   image: node:20.12.2
   container_name: backend
   working_dir: /app
   ports:
     - "8080:8080"
   volumes:
     - ./backend:/app
   restart: unless-stopped
   command: sh -c "yarn install && yarn start"

  # FRONTEND
  frontend:
   build:
     context: ./frontend
   image: node:20.12.2
   container_name: frontend
   working_dir: /app
   volumes:
     - ./frontend:/app
   ports:
     - "4200:4200"
   restart: unless-stopped
   command: sh -c "yarn install && yarn start"
   depends_on:
     - backend


