version: '3'
services:
#BACKEND
  backend:
   build:
     context: ./backend
   image: node:latest
   container_name: backend
   working_dir: /app
   ports:
     - "8080:8080"
   volumes:
     - ./backend:/app
   restart: unless-stopped
   command: sh -c "yarn install && yarn start"


